version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  lab2-service:
    restart: always
    build:
      context: ./lab2-service
    ports:
      - 8000:8000
    depends_on:
      - mysql-db